from wtforms import Form, StringField, TextAreaField, validators, RadioField, SelectMultipleField
# from flask import Flask, render_template
# from flask_wtf import Form
# from wtforms.fields import DateField
# from flask_bootstrap import Bootstrap
from datetime import datetime

class SubmissionForm(Form):
    # Date = DateField(id='datepick',default="2020-05-27")
    email = StringField('Title', [validators.Length(min=0, max=100)],default = '*youremail@gmail.com*')
    income_level = RadioField('Title', coerce=int, choices=[('5','$0 to $40,000'),('4','$40,001 to $65,000'),('3','$65,001 to $85,000'), ('2','$85,001 to $100,000'), ('1','$100,001 or more')])
    sector_preference = RadioField('Title', coerce=int, choices=[('5','Healthcare'),('4','Financial'),('3','Tech'), ('2','Consumer'), ('1','Communications')])
    citizenship = RadioField('Title', coerce=int, choices=[('0','No'),('1','Yes'),('2','Decline to answer')])
    education = RadioField('Title', coerce=int, choices=[('5','High School Diploma'),('4','Bachelors Degree'),('3','Post-Bac'), ('2','Masters'), ('1','Doctorate')])
    experience_years = RadioField('Title', coerce=int, choices=[('5','0 to 1 years'),('4','1 to 3 years'),('3','3 to 5 years'), ('2','5 to 10 years'), ('1','More than 10 years')])
    periodicals = SelectMultipleField('Title', coerce=int, choices=[('5','Wall Street Journal'),('4','MarketWatch'),('3','Economist'), ('2','SeekingAlpha'), ('1','Financial Times')])
    aspirations = SelectMultipleField('Title', coerce=int, choices=[('5','Hobby / Recreation'),('4','Income source'),('3','Career'), ('2','Retirement'), ('1','Education / Research')])
    diversification = RadioField('Title', coerce=int, choices=[('5','No'),('1','Yes')])
    brokerage_acct = RadioField('Title', coerce=int, choices=[('0','No'),('1','Yes')])
    interested_in_learning = RadioField('Title', coerce=int, choices=[('0','No'),('1','Yes')])
    scenario_1 = RadioField('Title', coerce=int, choices=[('5','debt holder'),('1','equity holder')])
    scenario_2 = RadioField('Title', coerce=int, choices=[('5','fall'),('1','rise')])
    port_diversified = RadioField('Title', coerce=int, choices=[('5','no'),('1','yes')])
    safest_asset = RadioField('Title', coerce=int, choices=[('5','real estate'),('1','ethereum'), ('4','gold'),('1','british pound')])
    income_drawing = RadioField('Title', coerce=int, choices=[('5','Not for at-least 20 years'),('4','10 to 20 years'),('3','5 to 10 years'), ('2','Not now, but within 5 years'), ('1','Immediately')])
    fin_info = StringField('Title', [validators.Length(min=0, max=100)],default = '*Enter Source*')
    return_expectations = RadioField('Title', coerce=int, choices=[('5','Aggressive growth'),('4','Significant growth'),('3','Moderate growth'), ('2','Mild growth'), ('1','Break-even')])
    normal_expectations = RadioField('Title', coerce=int, choices=[('5','Outperform the stock market'),('4','Track to the stock market'),('3','Slightly trail the stock market'), ('2','Grow moderately'), ('1','Grow with caution')])
    poor_expectations = RadioField('Title', coerce=int, choices=[('5','To lose money'),('4','To make very little or nothing'),('3','To make out a little gain'), ('2','To make a modest gain'), ('1','To be affected little by the stock market')])
    three_yr_attitude = RadioField('Title', coerce=int, choices=[('5','I can tolerate a large loss'),('4','I can tolerate a moderate loss'),('3','I can tolerate a small loss'), ('2','It would be hard dealing with a loss'), ('1','I need to see at least a little return')])
    three_month_attitude = RadioField('Title', coerce=int, choices=[('5','I would not worry about losses in that time frame'),('4','A loss of more than 10% would concern me'),('3','I can only tolerate small short-term losses'), ('2','I would have a hard time stomaching any issues'), ('1','I would not be able to tolerate any issues')])
    age = RadioField('Title', coerce=int, choices=[('5','Less than 45'),('4','45 to 55'),('3','56 to 65'), ('2','66 to 75'), ('1','75 or older')])
    # Open = StringField('Title', [validators.Length(min=0, max=30)],default = 287.75)
    # High = StringField('Title', [validators.Length(min=0, max=30)], default = 289.779999)
    # Low = StringField('Title', [validators.Length(min=0, max=30)],default = 287.130005)
    # Close = StringField('Title', [validators.Length(min=0, max=30)], default = 287.679993)
    # Volume = StringField('Title', [validators.Length(min=0, max=30)], default = 75250400)
    # T3_Vol_Diff = StringField('Title', [validators.Length(min=0, max=30)], default = 5622800)
    # T3_Close_Diff = StringField('Title', [validators.Length(min=0, max=30)], default = -4.109986)
    # T3_Open_Diff = StringField('Title',  [validators.Length(min=0, max=30)], default = -7.01001)
    # T2_Vol_Diff = StringField('Title',  [validators.Length(min=0, max=30)], default = 4319500)
    # T2_Close_Diff = StringField('Title', [validators.Length(min=0, max=30)], default = -1.489991)
    # T2_Open_Diff = StringField('Title', [validators.Length(min=0, max=30)], default = -1.109985)
    # T1_Vol_Diff = StringField('Title', [validators.Length(min=0, max=30)], default = -1617800)
    # T1_Close_Diff = StringField('Title', [validators.Length(min=0, max=30)], default = -3.429993)
    # T1_Open_Diff = StringField('Title', [validators.Length(min=0, max=30)], default = 0.290009)
    # Prior_Day_Vert_Delta_Ratio = StringField('Title', [validators.Length(min=0, max=30)], default = 0.566239)
    # Retracement_Signal = StringField('Title', [validators.Length(min=0, max=30)], default = 0.20754311)
    # Prior_Day_Derivative = StringField('Title', [validators.Length(min=0, max=30)], default = -0.0184704)